name: docx
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_quill: ^10.8.5
  url_launcher: ^6.3.1
  quill_native_bridge: ^10.7.9
  flutter_keyboard_visibility_temp_fork: ^0.1.3
  pdf: ^3.11.1
  path_provider: ^2.1.5
  printing: ^5.13.4
  vsc_quill_delta_to_html: ^1.0.5
  #flutter_html_to_pdf: ^0.7.0
  flutter_quill_to_pdf: ^2.2.5
  animated_text_kit: ^4.2.2
  file_picker: ^6.1.1
  google_fonts: ^6.2.1
  #html_editor_enhanced: ^2.6.0
  #html_editor_enhanced_android_fix: ^1.0.0+3
  #html_editor_plus: ^0.0.5
  htmltopdfwidgets: ^1.0.4
  html_to_pdf: ^0.8.1
  #flutter_widget_from_html: ^0.15.3
  uuid: ^4.5.1
  flutter_inappwebview: ^6.1.5
  fluttertoast: ^8.2.8
  flutter_pdfview: ^1.3.4
  pdf_render: ^1.4.12
  flutter_spinkit: ^5.2.1
  permission_handler: ^11.3.1
  share_plus: ^10.1.2
  package_info_plus: ^8.1.1
  downloadsfolder: ^1.1.0
  quill_html_editor: ^2.2.8
  flutter_widget_from_html_core: ^0.15.2
  media_scanner:
    git:
      url: https://github.com/wukgdu/media_scanner.git
      ref: efe757c





dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^5.0.0
  #lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 700

    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 700

    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 300
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 700




